In [7]:
#import numpy and pandas
import numpy as np
import pandas as pd

#load data with provided code snippet
filename = 'https://raw.githubusercontent.com/jtopor/DAV-5400/master/Project1/hflights.csv'
df  = pd.read_csv(filename)

In [16]:
print(df.columns,'\n')
print(df.shape)

Index(['Year', 'Month', 'DayofMonth', 'DayOfWeek', 'DepTime', 'ArrTime',
       'UniqueCarrier', 'FlightNum', 'TailNum', 'ActualElapsedTime', 'AirTime',
       'ArrDelay', 'DepDelay', 'Origin', 'Dest', 'Distance', 'TaxiIn',
       'TaxiOut', 'Cancelled', 'CancellationCode', 'Diverted'],
      dtype='object')

(20000, 21)

In [11]:
df.describe()

,Year,Month,DayofMonth,DayOfWeek,DepTime,ArrTime,FlightNum,ActualElapsedTime,AirTime,ArrDelay,DepDelay,Distance,TaxiIn,TaxiOut,Cancelled,Diverted
count,20000.0,20000.000000,20000.000000,20000.000000,19785.000000,19766.000000,20000.000000,19738.000000,19738.000000,19738.000000,19785.000000,20000.000000,19766.000000,19780.000000,20000.000000,20000.000000
mean,2011.0,1.054500,16.319000,4.020300,1396.328228,1586.669382,1626.416900,126.795319,105.584355,5.205340,8.297700,772.899550,6.076546,15.134328,0.011200,0.001900
std,0.0,0.227007,9.025692,2.096904,441.598739,458.489922,1142.067143,60.158125,57.655970,25.383494,23.934218,458.640531,4.085732,7.046056,0.105238,0.043549
min,2011.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,35.000000,23.000000,-49.000000,-18.000000,127.000000,1.000000,4.000000,0.000000,0.000000
25%,2011.0,1.000000,8.000000,2.000000,1026.000000,1224.250000,582.000000,74.000000,54.000000,-8.000000,-3.000000,351.000000,4.000000,10.000000,0.000000,0.000000
50%,2011.0,1.000000,17.000000,4.000000,1416.000000,1620.000000,1644.000000,123.000000,102.000000,0.000000,1.000000,787.000000,5.000000,14.000000,0.000000,0.000000
75%,2011.0,1.000000,25.000000,6.000000,1801.000000,1955.000000,2536.000000,162.000000,138.000000,11.000000,10.000000,1034.000000,7.000000,18.000000,0.000000,0.000000
max,2011.0,2.000000,31.000000,7.000000,2335.000000,2400.000000,7037.000000,539.000000,499.000000,775.000000,780.000000,3904.000000,140.000000,78.000000,1.000000,1.000000

Index(['Year', 'Month', 'DayofMonth', 'DayOfWeek', 'DepTime', 'ArrTime',
       'UniqueCarrier', 'FlightNum', 'TailNum', 'ActualElapsedTime', 'AirTime',
       'ArrDelay', 'DepDelay', 'Origin', 'Dest', 'Distance', 'TaxiIn',
       'TaxiOut', 'Cancelled', 'CancellationCode', 'Diverted'],
      dtype='object')